stages:
  - deploy

deploy_to_maven_repo:
  stage: deploy
  image: hub.iquantex.com/base/maven:3.6.3-alpine-with-tools
  script:
    - mvn clean deploy -Dmaven.test.skip=true
  only:
    - master
    - /(ci\-)+.*$/
    - develop
    - tags
  tags:
    - sigma-dev
